---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: unifi
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      RUNAS_UID0: "true"
    image:
      repository: jacobalberty/unifi
      tag: v6.5.54
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${SVC_UNIFI_ADDR}
        ports:
          http:
            protocol: HTTPS
    persistence:
      data:
        enabled: true
        existingClaim: unifi-data
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "access-point"
        hosts:
          - host: "unifi.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "unifi.${SECRET_DOMAIN}"
            secretName: "unifi-${SECRET_DOMAIN//./-}-tls"
    resources:
      requests:
        cpu: 15m
        memory: 500Mi
      limits:
        memory: 750Mi
