---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dokuwiki
  namespace: organization
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: dokuwiki
      version: 12.0.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    dokuwikiUsername: alex
    existingSecret: dokuwiki-password
    service:
      type: ClusterIP
    persistence:
      existingClaim: dokuwiki-data
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hajimari.io/enable: "true"
        hajimari.io/icon: "file-document"
      hostname: "wiki.${SECRET_DOMAIN}"
      path: /
      certManager: true
      tls: true
