---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mopidy
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: wernight/mopidy
      tag: latest
    nameOverride: mopidy
    service:
      main:
        enabled: true
        ports:
          http:
            enabled: true
            port: 6680
            protocol: TCP
      icecast:
        enabled: true
        ports:
          icecast:
            enabled: true
            port: 8000
            protocol: TCP
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "playlist-music"
        hosts:
        - host: "mopidy.${SECRET_DOMAIN}"
          paths:
          - path: /
          - path: /listen
            pathType: Prefix
            service:
              name: mopidy-icecast
              port: 8000
        tls:
        - hosts:
          - "mopidy.${SECRET_DOMAIN}"
          secretName: "mopidy-${SECRET_DOMAIN//./-}-tls"
    persistence:
      mopidy-config:
        enabled: true
        type: custom
        mountPath: /config
        volumeSpec:
          configMap:
            name: mopidy-config
      icecast-config:
        enabled: true
        type: custom
        volumeSpec:
          configMap:
            name: icecast-config
      data:
        enabled: true
        existingClaim: mopidy-data
        mountPath: /var/lib/mopidy/local
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
      limits:
        memory: 750Mi
    additionalContainers:
      icecast:
        name: icecast
        image: vimagick/icecast:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 8000
        volumeMounts:
        - name: icecast-config
          mountPath: /etc/icecast.xml
          subPath: icecast.xml
        - name: icecast-config
          mountPath: /usr/share/icecast/web/silence.mp3
          subPath: silence.mp3
