---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zwavejs2mqtt
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zwavejs2mqtt
      version: 5.0.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/zwave-js/zwavejs2mqtt
      tag: 5.10.1
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "zwavejs2mqtt.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "zwavejs2mqtt.${SECRET_DOMAIN}"
            secretName: "zwavejs2mqtt-${SECRET_DOMAIN//./-}-tls"
    persistence:
      config:
        enabled: true
        existingClaim: zwavejs2mqtt-config
        mountPath: "/usr/src/app/store"
    resources:
      limits:
        smarter-devices/ttyUSB0: 1
      requests:
        smarter-devices/ttyUSB0: 1
