---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: smarter-device-manager
  namespace: devices
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: smarter-device-manager
      version: 6.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: registry.gitlab.com/arm-research/smarter/smarter-device-manager
      tag: v1.20.7
    config: |
      - devicematch: ^ttyUSB[0-9]*$
        nummaxdevices: 10
      - devicematch: ^video[0-9]*$
        nummaxdevices: 10
