---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homer
  namespace: media
spec:
  chart:
    spec:
      chart: homer
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home.flux-system
      version: 3.2.1
  interval: 10m0s
  values:
    ingress:
      enabled: true
      hosts:
        - host: homer.home.waibel.us
          paths:
            - path: /
              pathType: Prefix
