---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hyperion-ng
  namespace: media
spec:
  chart:
    spec:
      chart: hyperion-ng
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m0s
  values:
    securityContext:
      privileged: true
    additionalVolumeMounts:
      - name: led-usb
        mountPath: /dev/ttyUSB2
    additionalVolumes:
      - name: led-usb
        hostPath:
          path: /dev/ttyUSB2
    ingress:
      enabled: true
      hosts:
        - host: hyperion.home.waibel.us
          paths:
            - path: /
              pathType: Prefix
    persistence:
      config:
        enabled: true
        existingClaim: hyperion-ng-config
