apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  chart:
    spec:
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 6.3.1
  interval: 5m0s
  values:
    additionalVolumeMounts:
      - name: zwave-usb
        mountPath: /dev/ttyUSB0
    additionalVolumes:
      - name: zwave-usb
        hostPath:
          path: /dev/ttyUSB0
    ingress:
      enabled: true
      hosts:
        - host: hass.home.waibel.us
          paths:
            - path: /
              pathType: Prefix
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: app
              operator: In
              values:
              - zwave-controller
